name: Generate Keystore
on: workflow_dispatch # This allows you to run it manually with a button

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore
        run: |
          keytool -genkey -noprompt \
            -alias tesco-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore my-release.keystore \
            -storepass tesco123 \
            -keypass tesco123 \
            -dname "CN=Tesco Engineering, OU=Engineering, O=Tesco, L=Jubail, S=Eastern, C=SA"

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: my-keystore-file
          path: my-release.keystore
